services:
  - type: web
    name: energy-watchtower
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: DATA_API_KEY
        sync: false
      - key: MAPBOX_API_KEY
        sync: false
